### ISSUE TITLE
Stopiteration

### ISSUE THREAD

**Issue by Ahmedbargheet** [broadinstitute/StrainGE#11]
Hi, 

I am running straingr Prepare a concatenated reference
##############################################################
(straingr prepare-ref -s path/to/straingst/*.tsv \
   -p "path/to/refdir/{ref}.fa.gz" \
   -S path/to/straingst_db/similarities.tsv
   -o refs_concat.fasta)
##############################################################
I got this error message
####################################################################################################
  File "/cluster/home/ahmedbar/.conda/envs/strainge/lib/python3.7/site-packages/strainge/io/utils.py", line 109, in parse_straingst
    next(result_file)
StopIteration
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/home/ahmedbar/.conda/envs/strainge/bin/straingr", line 11, in <module>
    sys.exit(straingr_cli())
  File "/cluster/home/ahmedbar/.conda/envs/strainge/lib/python3.7/site-packages/strainge/cli/main.py", line 110, in __call__
    self.run(args)
  File "/cluster/home/ahmedbar/.conda/envs/strainge/lib/python3.7/site-packages/strainge/cli/registry.py", line 83, in run
    rc = subcommand_func(**args_dict)
  File "/cluster/home/ahmedbar/.conda/envs/strainge/lib/python3.7/site-packages/strainge/cli/straingr.py", line 154, in __call__
    parse_straingst(f))
  File "/cluster/home/ahmedbar/.conda/envs/strainge/lib/python3.7/collections/__init__.py", line 655, in update
    _count_elements(self, iterable)
  File "/cluster/home/ahmedbar/.conda/envs/strainge/lib/python3.7/site-packages/strainge/cli/straingr.py", line 153, in <genexpr>
    straingst_counter.update(strain['strain'] for strain in
RuntimeError: generator raised StopIteration
####################################################################################################
Could you please help with that?

**Comment by lrvdijk** [comment]
Oh I think I haven't updated prepare-ref yet to support the new StrainGST output format, I'll fix this soon!

**Comment by Ahmedbargheet** [comment]
Thanks.
Could you please inform me as soon as you fix it?
I will be waiting for you.

**Comment by lrvdijk** [comment]
A new version is available on PyPI, bioconda will be updated soon. Please list only the *.strains.tsv files now when running prepare-ref.
