### ISSUE TITLE
Division by Zero Error during Database Creation Step (straingst kmersim)

### ISSUE THREAD

**Issue by autpereira** [broadinstitute/StrainGE#17]
I've used ncbi-genome-download to download reference sequences from genbank, and followed the steps listed for the StrainGST database creation. However, when I get to comparing the kmer sets, each pair of kmer sets gives the following error:

line 39, in jaccard
    return intersection / (kmers1.size + kmers2.size - intersection)
ZeroDivisionError: division by zero

I'm not certain if this is an error on my end, or possibly an issue with the kmerization in the previous step. Thanks in advance for any assistance.

**Comment by MMAThijssen** [comment]
I also ran into the same error. The traceback:

```
2022-10-21 14:38:28,602 - INFO:root:Comparing List_monocytogenes_02-1103 vs List_monocytogenes_FDAARGOS_57...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 296, in __call__
    scores['subset2'] = comparison.subset(data2, data1)
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/comparison.py", line 61, in subset
    return intersection / kmers1.size
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bioinformatics/miniconda3/envs/strainge/bin/straingst", line 11, in <module>
    sys.exit(straingst_cli())
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
    self.run(args)
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
    rc = subcommand_func(**args_dict)
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 379, in __call__
    scores = list(pool.imap_unordered(runner, to_compute_iter,
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/bioinformatics/miniconda3/envs/strainge/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
ZeroDivisionError: division by zero
```

Hope you can help!

**Comment by MMAThijssen** [comment]
The issue for me was that the .fa.gz actually did not contain any sequences. After removing these cases, the script ran fine.

I used `zgrep -c '>' *.fa.gz > seq_count.txt` to get the number of sequences each .fa.gz contained and removed those with 0 sequences.
