### ISSUE TITLE
'utf-8' codec can't decode byte 0x89 in position 0

### ISSUE THREAD

**Issue by nick-youngblut** [broadinstitute/StrainGE#24]
I'm running StrainGE v1.3.3 on Ubuntu  22.04. 

Command:

```
straingst createdb -o db.hdf5 -f *.hdf5
```

Error:

```
 Traceback (most recent call last):
    File "/opt/conda/bin/straingst", line 11, in <module>
      sys.exit(straingst_cli())
    File "/opt/conda/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
      self.run(args)
    File "/opt/conda/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
      rc = subcommand_func(**args_dict)
    File "/opt/conda/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 569, in __call__
      for line in from_file:
    File "/opt/conda/lib/python3.9/codecs.py", line 322, in decode
      (result, consumed) = self._buffer_decode(data, self.errors, final)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

My command for kmer-ization of the genomes:

```
    for F in *.fna.gz; do 
      straingst kmerize -o ${F%.fa.gz}.hdf5 $F
    done
```

Given the unicode error, I tried uncompressing the genomes prior to the kmer step, but this did not help.

Notably, the `${F%.fa.gz}.hdf5` files generated form `straingst kmerize` are only 100-200 bytes in size. I don't know if that is normal.

**Comment by nick-youngblut** [comment]
My bad, I was using the `-f` flag for `straingst createdb`
