### ISSUE TITLE
ZeroDivisionError: division by zero when setting up DB for acinetobacter genus

### ISSUE THREAD

**Issue by AdrianLimaG** [broadinstitute/StrainGE#30]
Not sure how to resolve this issue, i am trying to setup a DB for only 1 genus listed above

straingst kmersim --all-vs-all -t 4 -S jaccard -S subset /strainge_db/*.hdf5 > similarities.tsv
2023-04-04 10:02:52,226 - INFO:root:Start computing pairwise similarities...
2023-04-04 10:02:52,226 - INFO:root:Loading k-mer sets...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/site-packages/strainge/cli/kmersets.py", line 296, in __call__
    scores['subset2'] = comparison.subset(data2, data1)
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/site-packages/strainge/comparison.py", line 65, in subset
    return intersection / kmers1.size
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/bin/straingst", line 11, in <module>
    sys.exit(straingst_cli())
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/site-packages/strainge/cli/main.py", line 110, in __call__
    self.run(args)
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/site-packages/strainge/cli/registry.py", line 83, in run
    rc = subcommand_func(**args_dict)
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/site-packages/strainge/cli/kmersets.py", line 379, in __call__
    scores = list(pool.imap_unordered(runner, to_compute_iter,
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/multiprocessing/pool.py", line 451, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/Caskroom/mambaforge/base/envs/STRAIN/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ZeroDivisionError: division by zero

**Comment by AdrianLimaG** [comment]
Same error as Issue 17, closing
