### ISSUE TITLE
Error in customising database through straingst

### ISSUE THREAD

**Issue by sahilrishav2** [broadinstitute/StrainGE#37]
Hello, 

I am trying to customize the database but I got stuck in this step `straingst cluster -i similarities.tsv -d -C 0.99 -c 0.90 --clusters-out clusters.tsv     strainge_db/*.hdf5 > references_to_keep.txt` and the warning shown is this 

> 2024-02-20 07:49:41,401 - INFO:root:Reading pairwise similarities...
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000192635.1 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000219665.2 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000233975.2 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000236125.2 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000349865.1 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000439225.1 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000442985.1 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000576515.1 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000648215.1 average ANI to other references is 0.0%, possibly mislabeled reference?
> 2024-02-20 07:49:41,405 - WARNING:root:rish_StrainScan_t3_GCA_000699125.1 average ANI to other references is 0.0%, possibly mislabeled reference?
  
**and finally this error i got** 

> 2024-02-20 07:49:41,410 - INFO:root:Picking a representive genome per cluster...

> Traceback (most recent call last):

  

> File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
>   File "index.pyx", line 159, in pandas._libs.index.IndexEngine.get_loc
> TypeError: '['rish_StrainScan_t3_GCA_000192635.1', 'rish_StrainScan_t3_GCA_000219665.2', 'rish_StrainScan_t3_GCA_000233975.2', 'rish_StrainScan_t3_GCA_000236125.2', 'rish_StrainScan_t3_GCA_000349865.1', 'rish_StrainScan_t3_GCA_000439225.1', 'rish_StrainScan_t3_GCA_000442985.1']' is an invalid key  
> 

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
>   File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'rish_StrainScan_t3_GCA_000192635.1'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/rishabh/anaconda3/envs/strainge/bin/straingst", line 11, in <module>
>     sys.exit(straingst_cli())
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/cli/main.py", line 110, in __call__
>     self.run(args)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/cli/registry.py", line 83, in run
>     rc = subcommand_func(**args_dict)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/cli/kmersets.py", line 517, in __call__
>     similarities = similarities.loc[(to_keep, to_keep), :].copy()
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexing.py", line 1185, in __getitem__
>     return self._getitem_tuple(key)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexing.py", line 1369, in _getitem_tuple
>     return self._getitem_lowerdim(tup)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexing.py", line 1042, in _getitem_lowerdim
>     return self._getitem_nested_tuple(tup)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexing.py", line 1154, in _getitem_nested_tuple
>     obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexing.py", line 1425, in _getitem_axis
>     locs = labels.get_locs(key)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 3513, in get_locs
>     item_indexer = self._get_level_indexer(
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 3391, in _get_level_indexer
>     idx = self._get_loc_single_level_index(level_index, key)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 2980, in _get_loc_single_level_index
>     return level_index.get_loc(key)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3809, in get_loc
>     raise KeyError(key) from err
> KeyError: 'rish_StrainScan_t3_GCA_000192635.1

'
 Any help would be appreciated.

**Comment by sahilrishav2** [comment]
Please consider my concern. It's urgent

**Comment by sahilrishav2** [comment]
solved by downgrading pandas and scipy packages.  https://github.com/broadinstitute/StrainGE/issues/12

**Comment by sahilrishav2** [comment]
But, now after this step, i got stuck: `straingst createdb -f references_to_keep.txt -o pan-genome-db.hdf5`

> Traceback (most recent call last):
>   File "/home/rishabh/anaconda3/envs/strainge/bin/straingst", line 11, in <module>
>     sys.exit(straingst_cli())
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/cli/main.py", line 110, in __call__
>     self.run(args)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/cli/registry.py", line 83, in run
>     rc = subcommand_func(**args_dict)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/cli/kmersets.py", line 587, in __call__
>     kset = kmertools.kmerset_from_hdf5(fname)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/strainge/kmertools.py", line 155, in kmerset_from_hdf5
>     with h5py.File(file_path, 'r') as h5:
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
>   File "/home/rishabh/anaconda3/envs/strainge/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 102, in h5py.h5f.open
> FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'MultiIndex([('home_rishabh_ref2_GCA_000006965_1', ...),.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
>

**Comment by sahilrishav2** [comment]
solved that issue by modifying the line `kset = kmertools.kmerset_from_hdf5(fname + '.hdf5')`  to  `kset = kmertools.kmerset_from_hdf5(fname)`
